### ISSUE TITLE
About gopoll benchmark

### ISSUE THREAD

**Issue by helios741** [bytedance/gopkg#111]
### Question

请问有没有[gopool](https://github.com/bytedance/gopkg/tree/develop/util/gopool)和通过channel实现goroutine pool的性能对比，个人认为这个锁太大了：
1、 P的数量越多，channel的优势会优于锁
2、 如果goroutine创建速度快，锁等待会更高

感觉参照runtime，通过[runtime.LockOSThread](https://pkg.go.dev/runtime#LockOSThread)单独占几个系统线程，去处理这件事情（每次从全局的tasks中拿1/n的task），效率会更高，因为不会被runtime抢占。

**Comment by PureWhiteWu** [comment]
1. 有，sync.Mutex 性能更好，因为 channel 可以认为是 sync.Mutex + 一堆额外逻辑，所以性能肯定比 sync.Mutex 要差。
2. 不可以这么做，会有问题的： 调用 runtime.LockOSThread 期间不能持有锁，但是业务代码肯定需要锁；同时不能保证所有 goroutine 都在 gopool 下管理。

**Comment by helios741** [comment]
@PureWhiteWu 有可以公开的数据么😄

**Comment by PureWhiteWu** [comment]
> @PureWhiteWu 有可以公开的数据么😄

你可以测试一下，代码都是公开的。

**Comment by helios741** [comment]
> 调用 runtime.LockOSThread 期间不能持有锁，但是业务代码肯定需要锁；

请问这个结论是如何得出的，看代码只是占用了个线程而已，和能不能用mutex没关系吧

> 同时不能保证所有 goroutine 都在 gopool 下管理。

请问这个为什么不能保证？

**Comment by PureWhiteWu** [comment]
> 请问这个结论是如何得出的，看代码只是占用了个线程而已，和能不能用mutex没关系吧

抱歉，记混了，LockOSThread 可以用锁，procPin 不能用锁。

> 请问这个为什么不能保证？

因为总有场景以及业务会直接 go 出去 goroutine 的，这个没有好的办法进行限制，也不应该限制。
