### ISSUE TITLE
possible to show an example of passing value / reference?

### ISSUE THREAD

**Issue by hiqsociety** [bytedance/gopkg#119]
### Question

possible to show an example of passing value / reference?

nice work by the way, i've tested against 
https://github.com/panjf2000/ants

and found this to be faster but not sure if there are any significant difference between the two?

**Comment by PureWhiteWu** [comment]
Hi, maybe you can use closures like this:
```go
value := "some value"

gopool.Go(func() {
    value ...
})

// or 
value2 := "some value 2"

gopool.Go(func() {
    &value ...
})
```

**Comment by hiqsociety** [comment]
1. thx for the quick feedback,
2. i'm surprised the variable still works inside gopool that way.
3. do i have to set the size of the gopool or do u hv a setting for the size?

**Comment by PureWhiteWu** [comment]
Answered in another issue.
