### ISSUE TITLE
is the latest 1.18 go routine faster than this?  just curious coz it seems faster etc now

### ISSUE THREAD

**Issue by hiqsociety** [bytedance/gopkg#121]
### Question

is the latest 1.18 go routine faster than this?

just curious coz it seems faster etc now

**Comment by PureWhiteWu** [comment]
No, the function of gopool is not only reuse the goroutine, but also limit the number of goroutine.
For example in CPU-heavy jobs, to limit the number of goroutines can greatly decrease the need to do context switches, and thus improve the performance.
If you change the `DoCopyStack` depth to 10000 in the `gopool_test.go`, you may find that gopool is much more faster than native goorutine:
```
func DoCopyStack(a, b int) int {
	if b < 10000 {
		return DoCopyStack(0, b+1)
	}
	return 0
}
```

result:

```
goos: darwin
goarch: arm64
pkg: github.com/bytedance/gopkg/util/gopool
BenchmarkPool-10    	      15	  73215625 ns/op	  234532 B/op	   10071 allocs/op
BenchmarkGo-10      	       2	 579915708 ns/op	  921604 B/op	   11625 allocs/op
PASS
ok  	github.com/bytedance/gopkg/util/gopool	3.923s
```
