### ISSUE TITLE
feature request: WorkerCount() for gopool

### ISSUE THREAD

**Issue by lvsz1** [bytedance/gopkg#136]
### Summary

gopool是否可以开放WorkerCount()接口，用于业务监控gopool内goroutines数量，为gopool SetCap阈值提供依据

### Motivation

服务由于某些原因偶发Goroutines毛刺，导致CPU&Mem瞬间上涨，影响服务稳定性。因此想基于gopool.SetCap限制Goroutines数量，但Cap的阈值不太好确定(服务可以提供整个实例的Goroutines数量，但无法确定gopool协程池部分的Goroutines数量)。

**Comment by PureWhiteWu** [comment]
看着应该可以，你有意愿提个 pr 来加一下么？
