### ISSUE TITLE
a little improvement for `cacheRemap16Byte`

### ISSUE THREAD

**Issue by shadw3002** [bytedance/gopkg#181]
### Summary

it seems that collection LSCQ use function [`cacheRemap16Byte`](https://github.com/bytedance/gopkg/blob/7f5f1dee0b1e5f22fdd6cc374aa94e2871c25f5a/collection/lscq/util.go#LL58C6-L58C22)  to remap index used by SCQ, to do best effort to avoid false-sharing, maybe we could refer to folly UnboundedQueue's [`index`](https://github.com/facebook/folly/blob/ec297b748575e8ab86333899295715e6e85f909d/folly/concurrency/UnboundedQueue.h#LL672C14-L672C14), to remap index with less instructions. 

however, i see no noticeable change in performance via BenchmarkDefault, perhaps because the function is not on the critical path.

### Motivation

improve `cacheRemap16Byte` with less instructions

### Explanation

# Why it works?

for `scqsize = 2^n`, and `k = 2*m + 1`, define `remap(i)=k*i % scqsize` we can prove that: for any `abs(i_1 - i_2) < scqsize`, if `i_1 != i_2`, than `remap(i_1) != remap(i_2)`. 

this property makes remap() one-to-one map any `i` in `[x, x + scqsize)` to `[0, scqsize)`. 

# Compare Assembly Code

```go
package main

const (
	scqsize       = 1 << 16
	cacheLineSize = 64
)

func cacheRemap16ByteA(index uint64) uint64 {
	const cacheLineSize = cacheLineSize / 2
	rawIndex := index & uint64(scqsize-1)
	cacheLineNum := (rawIndex) % (scqsize / uint64(cacheLineSize))
	cacheLineIdx := rawIndex / (scqsize / uint64(cacheLineSize))
	return cacheLineNum*uint64(cacheLineSize) + cacheLineIdx
}

func cacheRemap16ByteB(index uint64) uint64 {
	return (index * 5) & (scqsize - 1)
}

func main() {}
```

```asm
        TEXT    main.cacheRemap16ByteA(SB), NOSPLIT|ABIInternal, $0-8
        FUNCDATA        $0, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)
        FUNCDATA        $1, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)
        FUNCDATA        $5, main.cacheRemap16ByteA.arginfo1(SB)
        FUNCDATA        $6, main.cacheRemap16ByteA.argliveinfo(SB)
        PCDATA  $3, $1
        MOVWLZX AX, CX
        ANDL    $2047, AX
        SHRQ    $11, CX
        SHLQ    $5, AX
        ADDQ    CX, AX
        RET
        TEXT    main.cacheRemap16ByteB(SB), NOSPLIT|ABIInternal, $0-8
        FUNCDATA        $0, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)
        FUNCDATA        $1, gclocals·g2BeySu+wFnoycgXfElmcg==(SB)
        FUNCDATA        $5, main.cacheRemap16ByteB.arginfo1(SB)
        FUNCDATA        $6, main.cacheRemap16ByteB.argliveinfo(SB)
        PCDATA  $3, $1
        LEAQ    (AX)(AX*4), CX
        MOVWLZX CX, AX
        RET
```

**Comment by zhangyunhao116** [comment]
> it seems that collection LSCQ use function [cacheRemap16Byte](https://github.com/bytedance/gopkg/blob/7f5f1dee0b1e5f22fdd6cc374aa94e2871c25f5a/collection/lscq/util.go#LL58C6-L58C22) to remap [index](https://github.com/facebook/folly/blob/ec297b748575e8ab86333899295715e6e85f909d/folly/concurrency/UnboundedQueue.h#LL672C14-L672C14) used by SCQ, to do best effort to avoid false-sharing, maybe we could refer to folly UnboundedQueue's index, to remap index with less instructions.

Looks like they are not the same function.
```
package main

const (
	scqsize       = 128
	cacheLineSize = 64
)

func cacheRemap16ByteA(index uint64) uint64 {
	const cacheLineSize = cacheLineSize / 2
	rawIndex := index & uint64(scqsize-1)
	cacheLineNum := (rawIndex) % (scqsize / uint64(cacheLineSize))
	cacheLineIdx := rawIndex / (scqsize / uint64(cacheLineSize))
	return cacheLineNum*uint64(cacheLineSize) + cacheLineIdx
}

func cacheRemap16ByteB(index uint64) uint64 {
	return (index * 5) & (scqsize - 1)
}

func main() {
	for i := uint64(0); i < 10; i++ {
		if cacheRemap16ByteA(i) != cacheRemap16ByteB(i) {
			println(cacheRemap16ByteA(i), cacheRemap16ByteB(i))
		}
	}
}
```
Output:
```
32 5
64 10
96 15
1 20
33 25
65 30
97 35
2 40
34 45
```
We can see that 32 64 96 is NOT in the same cache line, but 5 10 15 is in the same cache line (false sharing).

>however, i see no noticeable change in performance via BenchmarkDefault, perhaps because the function is not on the critical path.

The `cacheRemap` is an improvement only for multiple-cores(`+20%`), for single-core, it is a performance degradation(`-15%`). You can run the benchmark with different cores(and disable or enable the `cacheRemap`).

**Comment by shadw3002** [comment]
> Looks like they are not the same function.

Yes, versionB provides another way to remap index. 

> We can see that `0 32 64 96` is NOT in the same cache line, but `0 5 10 15` is in the same cache line (false sharing).

It seems that the result of `cacheRemap16Byte` is used to index `[scqsize]scqNodePointer`, and `sizeof(scqNodePointer) == 16 B`, so I think `4 * 16 B` gap is enough to make `ring[0]` and `ring[5]` in different cacheline.
